"use client";
import { useState } from "react";
import { Eye, EyeOff } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { GoogleButton } from "./GoogleButton";

type Props = { onSignup: () => void; onForgot: () => void; onSuccess: () => void };
const field = "mt-1 w-full rounded-lg border border-[#1E5631]/20 bg-white px-3.5 py-3 text-sm text-[#173522] outline-none transition placeholder:text-[#173522]/40 focus:border-[#4F8A3F] focus:ring-3 focus:ring-[#4F8A3F]/15";
const message = (error: unknown) => error instanceof Error ? error.message.replace("Firebase: ", "") : "Unable to sign in. Please try again.";

export default function LoginForm({ onSignup, onForgot, onSuccess }: Props) {
  const { login, googleLogin } = useAuth(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [remember, setRemember] = useState(true); const [show, setShow] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setLoading(true); try { await login(email.trim(), password, remember); onSuccess(); } catch (err) { setError(message(err)); } finally { setLoading(false); } };
  const google = async () => { setError(""); setLoading(true); try { await googleLogin(); onSuccess(); } catch (err) { setError(message(err)); } finally { setLoading(false); } };
  return <form onSubmit={submit} noValidate className="space-y-4"><div><label htmlFor="login-email" className="text-sm font-semibold text-[#173522]">Email or Phone</label><input id="login-email" type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" className={field} required />{email && !/^\S+@\S+\.\S+$/.test(email) && <p className="mt-1 text-xs text-red-700">Enter a valid email address.</p>}</div><div><div className="flex items-center justify-between"><label htmlFor="login-password" className="text-sm font-semibold text-[#173522]">Password</label><button type="button" onClick={onForgot} className="text-xs font-semibold text-[#4F8A3F] hover:text-[#1E5631]">Forgot password?</button></div><div className="relative"><input id="login-password" type={show ? "text" : "password"} autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Enter your password" className={field} required minLength={6}/><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#1E5631]/60" aria-label={show ? "Hide password" : "Show password"}>{show ? <EyeOff className="size-4"/> : <Eye className="size-4"/>}</button></div></div><label className="flex items-center gap-2 text-sm font-semibold text-[#173522]/75"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} className="size-4 accent-[#1E5631]" />Remember me</label>{error && <p role="alert" className="rounded-lg bg-red-50 px-3 py-2 text-xs text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-lg bg-[#1E5631] py-3 text-sm font-bold text-white transition hover:bg-[#174526] disabled:cursor-not-allowed disabled:opacity-60">{loading ? "Signing in..." : "Login"}</button><div className="flex items-center gap-3 py-1 text-xs text-[#173522]/45"><span className="h-px flex-1 bg-[#1E5631]/15"/>or<span className="h-px flex-1 bg-[#1E5631]/15"/></div><GoogleButton onClick={google} loading={loading}/><p className="pt-1 text-center text-sm text-[#173522]/65">New to Aram Narpavi Herbals? <button type="button" onClick={onSignup} className="font-bold text-[#1E5631] hover:text-[#E69500]">Create an account</button></p></form>;
}
